USE HQTCSDL2
GO

-- Truong hop: 16
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION datMon
	IF ((SELECT SOLUONG FROM MON where ID = 1) < 1)
	BEGIN
		RAISERROR(N'Số lượng món đã hết', 1, 16)
		ROLLBACK
	END

	declare @donHangID int
	-- Tao don hang
	INSERT INTO DONHANG (ID_KHACH_HANG, ID_TAI_XE, ID_CHI_NHANH, TRANGTHAI)
	VALUES (1, NULL, 3, 'Cho xac nhan')

	-- Them tuy chon mon
	SELECT @donHangID = SCOPE_IDENTITY()
	INSERT INTO CHITIETDONHANG (MADON, ID_TUY_CHON, SO_LUONG, GIA_TIEN)
	VALUES (@donHangID, 


COMMIT