use HQTCSDL2
go

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION xacNhanHopDong
	UPDATE HOPDONG
	SET DA_XAC_NHAN = 1, TG_XAC_NHAN = GETDATE(), TG_HET_HIEU_LUC = DATEADD(year, 1, GETDATE())
	WHERE MA_SO_THUE='8271892819'

	WAITFOR DELAY '00:00:07'
--gia lap loi -> rollback
ROLLBACK